image: node:12.19.0-alpine

pipelines:
  branches:
    master:
       - step:
           name: "[PROD] Deploy to AWS"
           caches:
             - node
           script:
             - apk add python3 python3-dev
             - npm install -g serverless && npm install
             - serverless config credentials --stage prod --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
             - serverless deploy --stage prod