# For full config options, check the docs:
# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: learn-serverless

frameworkVersion: '2'

package:
  individually: true  # for each lambda to be packaged individually

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-central-1
  environment:
    USERS_TABLE_NAME: users_${self:custom.currentStage}
    COGNITO_CLIENT_ID: 
      Ref: CognitoUserPoolClient
  iamRoleStatements:
      - Effect: "Allow"
        Action:
         - dynamodb:*
        Resource: arn:aws:dynamodb:eu-central-1:343179190615:table/users_dev

custom:
  currentStage: ${opt:stage, self:provider.stage, 'dev'}
  userPoolName: user-pool-${self:custom.currentStage}
  userPoolClientName: user-pool-client-${self:custom.currentStage}

functions:
  sign_up:
    handler: code/sign_up/sign_up.handler
    layers:
      - { Ref: BasicLambdaLayer }
    events:
      - http:
          path: /users/sign_up
          method: post
          cors: true
    package:
      exclude:
        - ./**
      include:
        - code/sign_up/**

  custom_message:
    handler: code/custom_verification_message/custom_message.handler
    events:
      - cognitoUserPool:
          pool: ${self:custom.userPoolName}
          trigger: CustomMessage
          existing: true
    package:
      exclude:
        - ./**
      include:
        - code/custom_verification_message/**

  add:
    handler: code/addition/add.add
    layers:
      - { Ref: BasicLambdaLayer }
    events:
      - http:
          path: /calculations/add
          method: post
          cors: true
    package:
      exclude:
        - ./**
      include:
        - code/addition/**

  subtract:
    handler: code/subtraction/subtract.subtract
    layers:
      - { Ref: BasicLambdaLayer }
    events:
      - http:
          path: /calculations/subtract
          method: post
          cors: true
    package:
      exclude:
        - ./**
      include:
        - code/subtraction/**

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    CognitoUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        MfaConfiguration: OFF
        UserPoolName: ${self:custom.userPoolName}
        UsernameAttributes:
          - email
        EmailConfiguration: 
          EmailSendingAccount: DEVELOPER  # COGNITO_DEFAULT
          #arn:aws:ses:us-east-1:1234567890:identity/john@myemail.com - like that for DEVELOPER
          #SourceArn: # sourceARN to verified email address in SES
          From: nataliia.dyshko@ukr.net
          SourceArn: arn:aws:ses:eu-west-1:343179190615:identity/nataliia.dyshko@ukr.net
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: True
            RequireNumbers: True
            RequireSymbols: False
            RequireUppercase: True
        AccountRecoverySetting:
          RecoveryMechanisms:
            -  Name: verified_email
               Priority: 1
        AutoVerifiedAttributes:
          - email
        UsernameConfiguration:
          CaseSensitive: False
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_LINK
        
    CognitoUserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: ${self:custom.userPoolClientName}
        GenerateSecret: False
        UserPoolId:
          Ref: CognitoUserPool

    CognitoUserPoolDomain:  # for verification link instead of code
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain: example199754
        UserPoolId:
          Ref: CognitoUserPool

layers:
  basic:
    path: ./code/layers/basic_layer
    name: basic_layer
    compatibleRuntimes:
      - python3.6
      - python3.7
      - python3.8