# For full config options, check the docs:
# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: learn-serverless

frameworkVersion: '2'

package:
  individually: true  # for each lambda to be packaged individually

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-central-1

functions:
  add:
    handler: code/addition/add.add
    layers:
      - { Ref: BasicLambdaLayer }
    events:
      - http:
          path: /calculations/add
          method: post
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
         - dynamodb:*
    package:
      exclude:
        - ./**
      include:
        - code/addition/**

  subtract:
    handler: code/subtraction/subtract.subtract
    layers:
      - { Ref: BasicLambdaLayer }
    events:
      - http:
          path: /calculations/subtract
          method: post
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
         - dynamodb:*
    package:
      exclude:
        - ./**
      include:
        - code/subtraction/**

layers:
  basic:
    path: ./code/layers/basic_layer
    name: basic_layer
    compatibleRuntimes:
      - python3.6
      - python3.7
      - python3.8